linters-settings:
  gofmt:
    simplify: false

linters:
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - scopelint
    - asciicheck
    - depguard
    - godot
    - gomodguard
    - goprintffuncname
    - maligned
    - nolintlint
    - rowserrcheck
    - exhaustive
    - exportloopref
    - gci
    - gocyclo
    - gofumpt
    - goheader
    - nestif
    - nlreturn
    - noctx
    - sqlclosecheck
    - testpackage
    - tparallel

issues:
  exclude:
    - G307 # gosec
  exclude-rules:
    - path: _test\.go
      linters:
        - maligned
        - bodyclose
