package apigen_test

import (
	"context"
	"log"

	"github.com/ktr0731/apigen"
	"github.com/ktr0731/apigen/curl"
)

func ExampleGenerate() {
	def := &apigen.Definition{
		Services: map[string][]*apigen.Method{
			"Dummy": []*apigen.Method{
				{
					Name:    "ListPosts",
					Request: curl.ParseCommand(`curl https://jsonplaceholder.typicode.com/posts`),
				},
				{
					Name:    "GetPost",
					Request: curl.ParseCommand(`curl https://jsonplaceholder.typicode.com/posts?id=1`),
				},
				{
					Name:      "GetPost2",
					Request:   curl.ParseCommand(`curl https://jsonplaceholder.typicode.com/posts/1`),
					ParamHint: "/posts/{postID}",
				},
			},
		},
	}
	if err := apigen.Generate(context.Background(), def); err != nil {
		log.Fatal(err)
	}
	// Output:
	// // Code generated by apigen; DO NOT EDIT.
	// // github.com/ktr0731/apigen
	//
	// package main
	//
	// import (
	// 	"context"
	// 	"fmt"
	// 	"net/url"
	//
	// 	"github.com/ktr0731/apigen/client"
	// )
	//
	// type DummyClient interface {
	// 	GetPost(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error)
	// 	GetPost2(ctx context.Context, req *GetPost2Request) (*GetPost2Response, error)
	// 	ListPosts(ctx context.Context, req *ListPostsRequest) (*ListPostsResponse, error)
	// }
	//
	// type dummyClient struct {
	// 	*client.Client
	// }
	//
	// func NewDummyClient(opts ...client.Option) DummyClient {
	// 	return &dummyClient{Client: client.New(opts...)}
	// }
	//
	// func (c *dummyClient) GetPost(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error) {
	// 	u, err := url.Parse("https://jsonplaceholder.typicode.com/posts")
	// 	if err != nil {
	// 		return nil, err
	// 	}
	//
	// 	var res GetPostResponse
	// 	err = c.Do(ctx, "GET", u, req, &res)
	// 	return &res, err
	// }
	//
	// func (c *dummyClient) GetPost2(ctx context.Context, req *GetPost2Request) (*GetPost2Response, error) {
	// 	u, err := url.Parse(fmt.Sprintf("https://jsonplaceholder.typicode.com/posts/%s", req.PostID))
	// 	if err != nil {
	// 		return nil, err
	// 	}
	//
	// 	var res GetPost2Response
	// 	err = c.Do(ctx, "GET", u, req, &res)
	// 	return &res, err
	// }
	//
	// func (c *dummyClient) ListPosts(ctx context.Context, req *ListPostsRequest) (*ListPostsResponse, error) {
	// 	u, err := url.Parse("https://jsonplaceholder.typicode.com/posts")
	// 	if err != nil {
	// 		return nil, err
	// 	}
	//
	// 	var res ListPostsResponse
	// 	err = c.Do(ctx, "GET", u, req, &res)
	// 	return &res, err
	// }
	//
	// type GetPostRequest struct {
	// 	ID string `name:"id"`
	// }
	//
	// type GetPostResponse []struct {
	// 	Body   string  `json:"body,omitempty"`
	// 	ID     float64 `json:"id,omitempty"`
	// 	Title  string  `json:"title,omitempty"`
	// 	UserID float64 `json:"userId,omitempty"`
	// }
	//
	// type GetPost2Request struct {
	// 	PostID string `name:"postID"`
	// }
	//
	// type GetPost2Response struct {
	// 	Body   string  `json:"body,omitempty"`
	// 	ID     float64 `json:"id,omitempty"`
	// 	Title  string  `json:"title,omitempty"`
	// 	UserID float64 `json:"userId,omitempty"`
	// }
	//
	// type ListPostsRequest struct{}
	//
	// type ListPostsResponse []struct {
	// 	Body   string  `json:"body,omitempty"`
	// 	ID     float64 `json:"id,omitempty"`
	// 	Title  string  `json:"title,omitempty"`
	// 	UserID float64 `json:"userId,omitempty"`
	// }
}
