package apigen_test

import (
	"context"
	"log"

	"github.com/ktr0731/apigen"
	"github.com/ktr0731/apigen/curl"
)

func ExampleGenerate() {
	def := &apigen.Definition{
		Methods: []*apigen.Method{
			{
				Service: "Dummy",
				Method:  "ListPosts",
				Request: curl.ParseCommand(`curl https://jsonplaceholder.typicode.com/posts`),
			},
			{
				Service: "Dummy",
				Method:  "GetPost",
				Request: curl.ParseCommand(`curl https://jsonplaceholder.typicode.com/post?id=1`),
			},
		},
	}
	if err := apigen.Generate(context.Background(), def); err != nil {
		log.Fatal(err)
	}
	// Output:
	// // Code generated by apigen; DO NOT EDIT.
	// // github.com/ktr0731/apigen
	//
	// package main
	//
	// import (
	// 	"context"
	// 	"github.com/ktr0731/apigen/client"
	// 	"net/http"
	// 	"net/url"
	// )
	//
	// type DummyClient interface {
	// 	GetPost(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error)
	// 	ListPosts(ctx context.Context, req *ListPostsRequest) (*ListPostsResponse, error)
	// }
	//
	// type dummyClient struct {
	// 	*client.Client
	// }
	//
	// func NewDummyClient(opts ...client.Option) DummyClient {
	// 	return &dummyClient{Client: client.New(append(opts, client.WithHeaders(headers))...)}
	// }
	//
	// func (c *dummyClient) GetPost(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error) {
	// 	u, err := url.Parse("https://jsonplaceholder.typicode.com/post")
	// 	if err != nil {
	// 		return nil, err
	// 	}
	//
	// 	var res GetPostResponse
	// 	err = c.Do(ctx, "GET", u, req, &res)
	// 	return &res, err
	// }
	//
	// func (c *dummyClient) ListPosts(ctx context.Context, req *ListPostsRequest) (*ListPostsResponse, error) {
	// 	u, err := url.Parse("https://jsonplaceholder.typicode.com/posts")
	// 	if err != nil {
	// 		return nil, err
	// 	}
	//
	// 	var res ListPostsResponse
	// 	err = c.Do(ctx, "GET", u, req, &res)
	// 	return &res, err
	// }
	//
	// type GetPostRequest struct {
	// 	ID string `name:"id"`
	// }
	//
	// type GetPostResponse struct{}
	//
	// type ListPostsRequest struct{}
	//
	// type ListPostsResponse []struct {
	// 	Body   string  `json:"body,omitempty"`
	// 	ID     float64 `json:"id,omitempty"`
	// 	Title  string  `json:"title,omitempty"`
	// 	UserID float64 `json:"userId,omitempty"`
	// }
}
