package apigen_test

import (
	"context"
	"log"

	"github.com/ktr0731/apigen"
	"github.com/ktr0731/apigen/curl"
)

func ExampleGenerate() {
	def := &apigen.Definition{
		Services: map[string][]*apigen.Method{
			"Dummy": {
				{
					Name:    "CreatePost",
					Request: curl.ParseCommand(`curl 'https://jsonplaceholder.typicode.com/posts' --data-binary '{"title":"foo","body":"bar","userId":1}'`),
				},
				{
					Name:    "GetPost",
					Request: curl.ParseCommand(`curl https://jsonplaceholder.typicode.com/posts?id=1`),
				},
				{
					Name:      "ListComments",
					Request:   curl.ParseCommand(`curl https://jsonplaceholder.typicode.com/posts/1/comments`),
					ParamHint: "/posts/{postID}/comments",
				},
				{
					Name:      "UpdatePost",
					Request:   curl.ParseCommand(`curl 'https://jsonplaceholder.typicode.com/posts/1' -X 'PUT' --data-binary '{"title":"foo","body":"bar","userId":1}'`),
					ParamHint: "/posts/{postID}",
				},
			},
		},
	}
	if err := apigen.Generate(context.Background(), def); err != nil {
		log.Fatal(err)
	}
	// Output:
	// // Code generated by apigen; DO NOT EDIT.
	// // github.com/ktr0731/apigen
	//
	// package main
	//
	// import (
	// 	"context"
	// 	"fmt"
	// 	"net/url"
	//
	// 	"github.com/ktr0731/apigen/client"
	// )
	//
	// type DummyClient interface {
	// 	CreatePost(ctx context.Context, req *CreatePostRequest) (*CreatePostResponse, error)
	// 	GetPost(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error)
	// 	ListComments(ctx context.Context, req *ListCommentsRequest) (*ListCommentsResponse, error)
	// 	UpdatePost(ctx context.Context, req *UpdatePostRequest) (*UpdatePostResponse, error)
	// }
	//
	// type dummyClient struct {
	// 	*client.Client
	// }
	//
	// func NewDummyClient(opts ...client.Option) DummyClient {
	// 	return &dummyClient{Client: client.New(opts...)}
	// }
	//
	// func (c *dummyClient) CreatePost(ctx context.Context, req *CreatePostRequest) (*CreatePostResponse, error) {
	// 	u, err := url.Parse("https://jsonplaceholder.typicode.com/posts")
	// 	if err != nil {
	// 		return nil, err
	// 	}
	//
	// 	var res CreatePostResponse
	// 	err = c.Do(ctx, "POST", u, req.Body, &res)
	// 	return &res, err
	// }
	//
	// func (c *dummyClient) GetPost(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error) {
	// 	query := url.Values{
	// 		"id": []string{req.ID},
	// 	}.Encode()
	//
	// 	u, err := url.Parse("https://jsonplaceholder.typicode.com/posts")
	// 	if err != nil {
	// 		return nil, err
	// 	}
	//
	// 	u.RawQuery = query
	//
	// 	var res GetPostResponse
	// 	err = c.Do(ctx, "GET", u, nil, &res)
	// 	return &res, err
	// }
	//
	// func (c *dummyClient) ListComments(ctx context.Context, req *ListCommentsRequest) (*ListCommentsResponse, error) {
	// 	u, err := url.Parse(fmt.Sprintf("https://jsonplaceholder.typicode.com/posts/%s/comments", req.PostID))
	// 	if err != nil {
	// 		return nil, err
	// 	}
	//
	// 	var res ListCommentsResponse
	// 	err = c.Do(ctx, "GET", u, nil, &res)
	// 	return &res, err
	// }
	//
	// func (c *dummyClient) UpdatePost(ctx context.Context, req *UpdatePostRequest) (*UpdatePostResponse, error) {
	// 	u, err := url.Parse(fmt.Sprintf("https://jsonplaceholder.typicode.com/posts/%s", req.PostID))
	// 	if err != nil {
	// 		return nil, err
	// 	}
	//
	// 	var res UpdatePostResponse
	// 	err = c.Do(ctx, "PUT", u, req.Body, &res)
	// 	return &res, err
	// }
	//
	// type CreatePostRequest struct {
	// 	Body *CreatePostRequestBody
	// }
	//
	// type CreatePostRequestBody struct {
	// 	Body   string  `json:"body,omitempty"`
	// 	Title  string  `json:"title,omitempty"`
	// 	UserID float64 `json:"userId,omitempty"`
	// }
	//
	// type CreatePostResponse struct {
	// 	ID float64 `json:"id,omitempty"`
	// }
	//
	// type GetPostRequest struct {
	// 	ID string
	// }
	//
	// type GetPostResponse []struct {
	// 	Body   string  `json:"body,omitempty"`
	// 	ID     float64 `json:"id,omitempty"`
	// 	Title  string  `json:"title,omitempty"`
	// 	UserID float64 `json:"userId,omitempty"`
	// }
	//
	// type ListCommentsRequest struct {
	// 	PostID string
	// }
	//
	// type ListCommentsResponse []struct {
	// 	Body   string  `json:"body,omitempty"`
	// 	Email  string  `json:"email,omitempty"`
	// 	ID     float64 `json:"id,omitempty"`
	// 	Name   string  `json:"name,omitempty"`
	// 	PostID float64 `json:"postId,omitempty"`
	// }
	//
	// type UpdatePostRequest struct {
	// 	PostID string
	// 	Body   *UpdatePostRequestBody
	// }
	//
	// type UpdatePostRequestBody struct {
	// 	Body   string  `json:"body,omitempty"`
	// 	Title  string  `json:"title,omitempty"`
	// 	UserID float64 `json:"userId,omitempty"`
	// }
	//
	// type UpdatePostResponse struct {
	// 	ID float64 `json:"id,omitempty"`
	// }
}
